name = "flottbook"
description = "A book theme inspired from GitBook/mdBook"
license = "MPL"
homepage = "https://github.com/target/"
min_version = "0.1"

[extra]
book_number_chapters = false

[author]
name = ""
homepage = ""
